dist: trusty
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
addons:
  sonarcloud:
    organization: "lucasmaliszewski"
    token: $SONAR_TOKEN
install:
  - pip3 install pytest
  - pip3 install --upgrade pip
script:
#  - pytest
  - sonar-scanner
