dist: trusty
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
jobs:
  include:
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2
      language: shell
addons:
  sonarcloud:
    organization: "lucasmaliszewski"
    token: $SONAR_TOKEN
install:
  - pip3 install pytest
  - pip3 install --upgrade pip
script:
#  - pytest
  - sonar-scanner
